import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col bg-[#fafaf9]">
        <div className="h-1 w-full bg-gradient-to-r from-teal-400 via-amber-300 to-rose-400" />
        <header className="bg-white border-b border-slate-200 sticky top-0 z-10">
          <nav className="max-w-5xl mx-auto flex items-center justify-between px-6 py-4">
            <Link
              href="/workshops"
              className="font-bold text-base tracking-tight text-slate-900"
            >
              WorkshopLab
            </Link>
            <div className="flex gap-6 text-sm font-medium text-slate-600">
              <Link href="/workshops" className="hover:text-slate-900">
                Workshops
              </Link>
              <Link href="/workshops/popular" className="hover:text-slate-900">
                Popular
              </Link>
              <Link href="/admin/workshops" className="hover:text-slate-900">
                Admin
              </Link>
            </div>
          </nav>
        </header>
        <main className="flex-1 max-w-5xl w-full mx-auto px-6 py-10">
          {children}
        </main>
      </body>
    </html>
  );
}
